---
galaxy_info:
  author: Abraham Snell
  description: Verify RHEL 10 ARM64 EC2 instance configuration
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "10"
  galaxy_tags:
    - rhel
    - rhel10
    - verification
    - testing

dependencies: []
